### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by FaresRAburas** [RiteshKH/Cursive_handwriting_recognition#1]
Hello RiteshKH
Appreciate your work, while executing model_build.py with your gzip folder I'm getting below error 
cannot found /emnist-letters-train-images-idx3-ubyte.gz

**Comment by RiteshKH** [comment]
Hi FaresRAburas
The training was done on EMNIST dataset, which can be easily downloaded from their official site. Since the dataset is too big in size I didn't add it in 'gzip' folder. Please download the dataset and add it in the gzip folder from "https://www.nist.gov/node/1298471/emnist-dataset"
