### ISSUE TITLE
Issue with Tensorflow

### ISSUE THREAD

**Issue by shrotriya** [RiteshKH/Cursive_handwriting_recognition#3]
Hi,

I am getting the below error while running the model.py file in pycharm.
Installed Tensorflow by the following command :
pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.8.0-py3-none-any.whl

Error which I am getting while running model.py is as follows:
**import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'**

Please can you suggest?
Thanks,
Shrotriya

**Comment by RiteshKH** [comment]
This issue usually comes with higher versions of Tensorflow. Changing the Tensorflow version to 1.5 or lower has solved the problem for few users.
https://stackoverflow.com/questions/44080677/no-module-named-pywrap-tensorflow-internal
