### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by nalrasheed** [RiteshKH/Cursive_handwriting_recognition#4]
Hello RiteshKH,

I am very impressed by your work and I wonder if you have publish any paper related to that code? I would like to read more details about the techniques you have applied for the character segmentation.

Thank you!

**Comment by RiteshKH** [comment]
Thank you for your interest. We are in the process of publishing the paper. Till then you can have a look at the Cursive_Handwriting_Recognition report attached in the code for details, although it's almost same as described in the readme. Sorry I couldn't include any further details.

Thanks.
